### ISSUE TITLE
Cake Tasks

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/AzureDevOpsKats#62]
- [x] 1 Cake.OpenCoverToCoberturaConverter
https://github.com/volak/Cake.OpenCoverToCoberturaConverter

- [x] 2 GitHub Pages 

**Plugin:** 
https://marketplace.visualstudio.com/items?itemName=AccidentalFish.githubpages-publish

**gh-pages**
https://stuartshay.github.io/AzureDevOpsKats/

```
  - task: GitHubPagesPublish@1
    inputs:
      docPath: 'docFx\*'
      githubusername: $(git_username)
      githubemail: $(git_email)
      githubaccesstoken: $(Nukeepeer_github_token)
      repositoryname: 'AzureDevOpsKats'
      branchname: 'gh-pages'
      commitmessage: 'Automated Release $(Release.ReleaseId)'

  - task: PowerShell@2
    inputs:
     targetType: 'inline'
     script: 'Write-Host "Hello World"
     Write-Host "$(git_username) | $(git_email) | $(Nukeepeer_github_token)"'

```
- [ ] 3  Publish to App Service

```
  - task: AzureRmWebAppDeployment@4
    inputs:
     ConnectionType: 'AzureRM'
     azureSubscription: 'Visual Studio Ultimate with MSDN (4ffc998e-322d-4b70-9e93-1515eed562c6)'
     appType: 'webApp'
     WebAppName: 'AzureDevOpsKats-Web'
     package: '$(Build.ArtifactStagingDirectory)/*.zip'
```

https://github.com/ttu/dotnet-fake-json-server
https://blog.ehn.nu/2019/05/accessing-azure-artifacts-feed-in-a-docker-build/
https://www.aaron-powell.com/posts/2019-05-24-azure-pipeline-templates-and-parameters/
